<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="6" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-08-27T14:17:01 IST" name="Default suite" finished-at="2021-08-27T14:17:01 IST" duration-ms="70">
    <groups>
    </groups>
    <test started-at="2021-08-27T14:17:01 IST" name="Default test" finished-at="2021-08-27T14:17:01 IST" duration-ms="70">
      <class name="stringcalc.tcalc">
        <test-method is-config="true" signature="init()[pri:0, instance:stringcalc.tcalc@79b06cab]" started-at="2021-08-27T14:17:01 IST" name="init" finished-at="2021-08-27T14:17:01 IST" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="allowline()[pri:0, instance:stringcalc.tcalc@79b06cab]" started-at="2021-08-27T14:17:01 IST" name="allowline" finished-at="2021-08-27T14:17:01 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- allowline -->
        <test-method signature="empty()[pri:0, instance:stringcalc.tcalc@79b06cab]" started-at="2021-08-27T14:17:01 IST" name="empty" finished-at="2021-08-27T14:17:01 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- empty -->
        <test-method signature="negativeexception()[pri:0, instance:stringcalc.tcalc@79b06cab]" started-at="2021-08-27T14:17:01 IST" name="negativeexception" finished-at="2021-08-27T14:17:01 IST" duration-ms="1" status="FAIL">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method tcalc.negativeexception()[pri:0, instance:stringcalc.tcalc@79b06cab] should have thrown an exception of type class java.lang.Exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method tcalc.negativeexception()[pri:0, instance:stringcalc.tcalc@79b06cab] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeexception -->
        <test-method signature="singleval()[pri:0, instance:stringcalc.tcalc@79b06cab]" started-at="2021-08-27T14:17:01 IST" name="singleval" finished-at="2021-08-27T14:17:01 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- singleval -->
        <test-method signature="twonum()[pri:0, instance:stringcalc.tcalc@79b06cab]" started-at="2021-08-27T14:17:01 IST" name="twonum" finished-at="2021-08-27T14:17:01 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- twonum -->
        <test-method signature="unnum()[pri:0, instance:stringcalc.tcalc@79b06cab]" started-at="2021-08-27T14:17:01 IST" name="unnum" finished-at="2021-08-27T14:17:01 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unnum -->
        <test-method signature="variablesep()[pri:0, instance:stringcalc.tcalc@79b06cab]" started-at="2021-08-27T14:17:01 IST" name="variablesep" finished-at="2021-08-27T14:17:01 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- variablesep -->
      </class> <!-- stringcalc.tcalc -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
